[uwsgi]
;http = 0.0.0.0:8080 この設定だと外部からアクセスできない（というかメモリが大量に使われて uWSGI がちゃんと動かないっぽい）
http-socket = 0.0.0.0:8080
chdir = /var/app/flask
module = app:app
processes = 1
threads = 1
master = false
vacuum = false
die-on-term = true
disable-logging = true
;limit-nofile = 4096 この設定を入れても http で指定してたらアクセスできない
